import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import styles from "../styles/Home.module.css";

export default function Home() {
    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.main}>
                <h1 className={styles.title}>
                    Welcome to{" "}
                    <Link href={"/"}>
                        <a>the Website!</a>
                    </Link>
                </h1>

                <p className={styles.description}>
                    This App is a demo version, check out the pages
                </p>

                <div className={styles.grid}>
                    <Link href={"/marketplace"}>
                        <a className={styles.card}>
                            <h2>Marketplace &rarr;</h2>
                            <p>
                                Search and filter all the products available in
                                our shop.
                            </p>
                        </a>
                    </Link>

                    <Link href={"/item"}>
                        <a className={styles.card}>
                            <h2>Examples &rarr;</h2>
                            <p>
                                Discover the product example page, its
                                information and features.
                            </p>
                        </a>
                    </Link>

                    <Link href={"/minter"}>
                        <a className={styles.card}>
                            <h2>NFT Minter &rarr;</h2>
                            <p>
                                See the form to create a new NFT on the Ethereum
                                blockchain.
                            </p>
                        </a>
                    </Link>

                    <div className={styles.card}>
                        <h2>Wallet &rarr;</h2>
                        <p>
                            Open the side menu and connect your Metamask wallet
                            to the website.
                        </p>
                    </div>
                </div>
            </main>

            <footer className={styles.footer}>
                <a
                    href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
                    target="_blank"
                    rel="noopener noreferrer"
                >
                    Powered by{" "}
                    <span className={styles.logo}>
                        <Image
                            src="/vercel.svg"
                            alt="Vercel Logo"
                            width={72}
                            height={16}
                        />
                    </span>
                </a>
            </footer>
        </div>
    );
}
